services:
  backend:
    build: ./backend
    container_name: server_box
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend/mysite/db.sqlite3:/app/db.sqlite3
      - ./backend/mysite/:/app/.
  frontend:
    build: ./frontend/gallery_projects
    container_name: react_box
    ports:
      - 3000:3000
    volumes:
      - ./frontend/gallery_projects:/app/
      - /app/node_modules
    stdin_open: true
    tty: true