# Generated by Django 5.2.2 on 2025-06-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_projects', '0002_alter_project_options_project_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='project_images'),
        ),
    ]
